title: Watershed Down
email: info@watersheddown.org
description: >-
  Watershed Down is dedicated to protecting and restoring our watershed areas, preventing illegal dumping, and preserving clean water sources.

baseurl: ""
url: "https://www.watersheddown.org"

# Social links
twitter_username: WatershedDownCA
instagram_username: WatershedDownCA
youtube: https://www.youtube.com/@WatershedDownCA
bluesky: https://bsky.app/profile/watersheddown.bsky.social

# Build settings
theme: minima
plugins:
  - jekyll-feed

